spring:
  config:
    activate:
      on-profile: "prod"

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
springfox:
  documentation:
    swagger-ui:
      base-url: "/api/v1/"
encrypt:
  salt: ${ENCRYPT_SALT}