spring:
  config:
    activate:
      on-profile: "local"

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/TodaysFail
    username: sa
    password:
  h2:
    console:
      enabled: true