name: Deploy to cloudtype
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: todays_fail/today_fail
          stage: dev
          yaml: |
            name: todaysfail-be
            app: java@11
            options:
              ports: 8080
              env:
                - name: TZ
                  value: Asia/Seoul
                - name: SPRING_PROFILES_ACTIVE
                  value: dev
                - name: DATASOURCE_HOST
                  value: ${{ secrets.DEV_DATASOURCE_HOST }}
                - name: DATASOURCE_PORT
                  value: ${{ secrets.DEV_DATASOURCE_PORT }}
                - name: DATASOURCE_USERNAME
                  value: ${{ secrets.DEV_DATASOURCE_USERNAME }}
                - name: DATASOURCE_PASSWORD
                  value: ${{ secrets.DEV_DATASOURCE_PASSWORD }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot